<?php

/**
 * UseCase Group metadata definitions
 *
 * Each group has:
 * - name: Unique identifier (matches key in permissions.php)
 * - display_name: Human-readable name (Japanese)
 * - description: Description of the group's purpose
 * - icon: Optional icon identifier for UI
 * - sort_order: Display order (lower = first)
 */

return [
    'Authorization' => [
        'display_name' => 'ロール・権限管理',
        'description' => 'ユーザーのロールと権限を管理します',
        'icon' => 'shield',
        'sort_order' => 1,
    ],
    'Users' => [
        'display_name' => 'ユーザー管理',
        'description' => 'ユーザーアカウントの作成・編集・削除を管理します',
        'icon' => 'users',
        'sort_order' => 2,
    ],
    'Category' => [
        'display_name' => 'カテゴリ管理',
        'description' => 'コンテンツのカテゴリ分類を管理します',
        'icon' => 'folder',
        'sort_order' => 10,
    ],
    'Tags' => [
        'display_name' => 'タグ管理',
        'description' => 'コンテンツのタグ付けを管理します',
        'icon' => 'tag',
        'sort_order' => 11,
    ],
    'News' => [
        'display_name' => 'ニュース管理',
        'description' => 'ニュース記事の作成・編集・公開を管理します',
        'icon' => 'newspaper',
        'sort_order' => 20,
    ],
    'Sessions' => [
        'display_name' => 'セッション管理',
        'description' => 'ユーザーのログインセッションを管理します',
        'icon' => 'key',
        'sort_order' => 3,
    ],
    'ChatGuest' => [
        'display_name' => 'ゲストチャット',
        'description' => 'ゲストユーザーとのチャット対応を管理します',
        'icon' => 'message-circle',
        'sort_order' => 30,
    ],
    'Chat' => [
        'display_name' => 'チャット',
        'description' => 'ユーザー間のチャット機能を管理します',
        'icon' => 'messages',
        'sort_order' => 31,
    ],
    'Plans' => [
        'display_name' => 'プラン管理',
        'description' => '料金プランの作成・編集を管理します',
        'icon' => 'credit-card',
        'sort_order' => 40,
    ],
    'MySns' => [
        'display_name' => 'SNS連携',
        'description' => 'SNSアカウントの連携を管理します',
        'icon' => 'share-2',
        'sort_order' => 50,
    ],
    'MySnsBot' => [
        'display_name' => 'SNSボット',
        'description' => 'SNS自動投稿ボットを管理します',
        'icon' => 'bot',
        'sort_order' => 51,
    ],
    'Dify' => [
        'display_name' => 'Dify連携',
        'description' => 'Dify AIプラットフォームとの連携を管理します',
        'icon' => 'cpu',
        'sort_order' => 60,
    ],
    'MediaUploads' => [
        'display_name' => 'メディアアップロード',
        'description' => '画像・動画のアップロードを管理します',
        'icon' => 'upload',
        'sort_order' => 70,
    ],
    'MediaFolders' => [
        'display_name' => 'メディアフォルダ',
        'description' => 'メディアファイルのフォルダ構造を管理します',
        'icon' => 'folder-open',
        'sort_order' => 71,
    ],
    'Notifications' => [
        'display_name' => '通知管理',
        'description' => 'システム通知の作成・送信を管理します',
        'icon' => 'bell',
        'sort_order' => 80,
    ],
    'Firebase' => [
        'display_name' => 'Firebase通知',
        'description' => 'Firebaseプッシュ通知を管理します',
        'icon' => 'flame',
        'sort_order' => 81,
    ],
    'PusherNotification' => [
        'display_name' => 'Pusher通知',
        'description' => 'リアルタイム通知を管理します',
        'icon' => 'zap',
        'sort_order' => 82,
    ],
    'Affiliates' => [
        'display_name' => 'アフィリエイト',
        'description' => 'アフィリエイトプログラムを管理します',
        'icon' => 'link',
        'sort_order' => 90,
    ],
    'Schedules' => [
        'display_name' => 'スケジュール管理',
        'description' => 'イベントスケジュールを管理します',
        'icon' => 'calendar',
        'sort_order' => 100,
    ],
    'ScheduleTags' => [
        'display_name' => 'スケジュールタグ',
        'description' => 'スケジュールのタグ分類を管理します',
        'icon' => 'calendar-check',
        'sort_order' => 101,
    ],
    'UserSchedule' => [
        'display_name' => 'ユーザースケジュール',
        'description' => 'ユーザー個人のスケジュールを管理します',
        'icon' => 'calendar-user',
        'sort_order' => 102,
    ],
    'Places' => [
        'display_name' => '場所管理',
        'description' => '店舗・会場などの場所情報を管理します',
        'icon' => 'map-pin',
        'sort_order' => 110,
    ],
    'Services' => [
        'display_name' => 'サービス管理',
        'description' => '提供サービスの情報を管理します',
        'icon' => 'briefcase',
        'sort_order' => 111,
    ],
    'SystemSetting' => [
        'display_name' => 'システム設定',
        'description' => 'アプリケーション全体の設定を管理します',
        'icon' => 'settings',
        'sort_order' => 5,
    ],
    'RankMaster' => [
        'display_name' => 'ランクマスター',
        'description' => 'ユーザーランクの定義を管理します',
        'icon' => 'award',
        'sort_order' => 120,
    ],
    'UserRank' => [
        'display_name' => 'ユーザーランク',
        'description' => 'ユーザーのランク情報を参照します',
        'icon' => 'trophy',
        'sort_order' => 121,
    ],
    'ExperienceHistory' => [
        'display_name' => '経験値履歴',
        'description' => 'ユーザーの経験値獲得履歴を管理します',
        'icon' => 'trending-up',
        'sort_order' => 122,
    ],
    'PointHistory' => [
        'display_name' => 'ポイント履歴',
        'description' => 'ユーザーのポイント獲得・使用履歴を管理します',
        'icon' => 'coins',
        'sort_order' => 123,
    ],
    'DailyBonus' => [
        'display_name' => 'デイリーボーナス',
        'description' => '毎日ログインボーナスを管理します',
        'icon' => 'gift',
        'sort_order' => 124,
    ],
    'UserPointDaily' => [
        'display_name' => 'ユーザーデイリーポイント',
        'description' => 'ユーザーの日次ポイント情報を管理します',
        'icon' => 'star',
        'sort_order' => 125,
    ],
    'UserPointAffiliate' => [
        'display_name' => 'アフィリエイトポイント',
        'description' => 'アフィリエイト経由のポイントを管理します',
        'icon' => 'users-plus',
        'sort_order' => 126,
    ],
    'AffiliateBonus' => [
        'display_name' => 'アフィリエイトボーナス',
        'description' => 'アフィリエイト報酬を管理します',
        'icon' => 'dollar-sign',
        'sort_order' => 127,
    ],
    'WorkManagement' => [
        'display_name' => 'ワーク管理',
        'description' => '作業・タスク管理機能を管理します',
        'icon' => 'clipboard-list',
        'sort_order' => 130,
    ],
    'UserWorkManagement' => [
        'display_name' => 'ユーザーワーク管理',
        'description' => 'ユーザーの作業記録を管理します',
        'icon' => 'clipboard-check',
        'sort_order' => 131,
    ],
    'CustomLink' => [
        'display_name' => 'カスタムリンク',
        'description' => 'カスタムリンクの作成・分析を管理します',
        'icon' => 'external-link',
        'sort_order' => 140,
    ],
    'AppSetting' => [
        'display_name' => 'アプリ設定',
        'description' => 'アプリケーション固有の設定を管理します',
        'icon' => 'sliders',
        'sort_order' => 6,
    ],
    'AppRelease' => [
        'display_name' => 'アプリリリース',
        'description' => 'アプリのバージョン・リリース情報を管理します',
        'icon' => 'package',
        'sort_order' => 7,
    ],
    'AppPage' => [
        'display_name' => 'アプリページ',
        'description' => 'アプリ内ページの管理を行います',
        'icon' => 'layout',
        'sort_order' => 8,
    ],
    'AishipProduct' => [
        'display_name' => 'Aiship商品',
        'description' => 'Aiship連携商品を管理します',
        'icon' => 'shopping-bag',
        'sort_order' => 150,
    ],
    'GroupPost' => [
        'display_name' => 'グループ投稿',
        'description' => 'グループ内の投稿を管理します',
        'icon' => 'message-square',
        'sort_order' => 160,
    ],
    'CommunityPost' => [
        'display_name' => 'コミュニティ投稿',
        'description' => 'コミュニティの投稿を管理します',
        'icon' => 'users-round',
        'sort_order' => 161,
    ],
    'MyPost' => [
        'display_name' => 'マイ投稿',
        'description' => '自分の投稿・タイムラインを管理します',
        'icon' => 'file-text',
        'sort_order' => 162,
    ],
    'NotificationPush' => [
        'display_name' => 'プッシュ通知',
        'description' => 'プッシュ通知の作成・送信を管理します',
        'icon' => 'send',
        'sort_order' => 83,
    ],
    'FcmToken' => [
        'display_name' => 'FCMトークン',
        'description' => 'Firebaseデバイストークンを管理します',
        'icon' => 'smartphone',
        'sort_order' => 84,
    ],
    'Member' => [
        'display_name' => '会員',
        'description' => '会員情報を管理します',
        'icon' => 'user-check',
        'sort_order' => 200,
    ],
    'Location' => [
        'display_name' => 'ロケーション',
        'description' => 'ロケーション情報を管理します',
        'icon' => 'store',
        'sort_order' => 202,
    ],
    'GolphLocation' => [
        'display_name' => 'ゴルフロケーション',
        'description' => 'ゴルフロケーションを管理します',
        'icon' => 'flag',
        'sort_order' => 203,
    ],
    'SaunaLocation' => [
        'display_name' => 'サウナロケーション',
        'description' => 'サウナロケーションを管理します',
        'icon' => 'flame',
        'sort_order' => 204,
    ],
    'Coupon' => [
        'display_name' => 'クーポン',
        'description' => 'クーポンを管理します',
        'icon' => 'ticket',
        'sort_order' => 205,
    ],
    'Term' => [
        'display_name' => '利用規約',
        'description' => '利用規約を管理します',
        'icon' => 'file-contract',
        'sort_order' => 206,
    ],
    'GolphPlan' => [
        'display_name' => 'ゴルフプラン',
        'description' => 'ゴルフプランを管理します',
        'icon' => 'list',
        'sort_order' => 207,
    ],
    'AvailabilitySlot' => [
        'display_name' => '空き枠',
        'description' => '空き枠スケジュールを管理します',
        'icon' => 'calendar',
        'sort_order' => 208,
    ],
    'Faq' => [
        'display_name' => 'FAQ',
        'description' => 'よくある質問を管理します',
        'icon' => 'help-circle',
        'sort_order' => 170,
    ],
    'StripeAccount' => [
        'display_name' => 'Stripeアカウント',
        'description' => 'Stripe決済アカウントを管理します',
        'icon' => 'credit-card',
        'sort_order' => 41,
    ],
    'StripeTransaction' => [
        'display_name' => 'Stripe取引',
        'description' => 'Stripe決済取引を参照・エクスポートします',
        'icon' => 'receipt',
        'sort_order' => 42,
    ],
    'PaymentTrigger' => [
        'display_name' => '決済トリガー',
        'description' => '決済時のアクションを管理します',
        'icon' => 'zap',
        'sort_order' => 44,
    ],
    'Product' => [
        'display_name' => '商品管理',
        'description' => '販売商品を管理します',
        'icon' => 'package',
        'sort_order' => 45,
    ],
    'Columns' => [
        'display_name' => 'コラム管理',
        'description' => 'コラム記事を管理します',
        'icon' => 'file-text',
        'sort_order' => 21,
    ],
    'Comments' => [
        'display_name' => 'コメント管理',
        'description' => 'コメントを管理します',
        'icon' => 'message-circle',
        'sort_order' => 180,
    ],
    'PostComment' => [
        'display_name' => '投稿コメント',
        'description' => '投稿へのコメントを管理します',
        'icon' => 'message-square-plus',
        'sort_order' => 181,
    ],
    'UserComment' => [
        'display_name' => 'ユーザーコメント',
        'description' => 'ユーザーへのコメントを管理します',
        'icon' => 'message-square-text',
        'sort_order' => 182,
    ],
    'Maintenance' => [
        'display_name' => 'メンテナンス',
        'description' => 'システムメンテナンス機能を管理します',
        'icon' => 'wrench',
        'sort_order' => 4,
    ],
    'AiApplication' => [
        'display_name' => 'AIアプリケーション',
        'description' => 'AIアプリケーションを管理します',
        'icon' => 'bot',
        'sort_order' => 61,
    ],
    'AiModelPrice' => [
        'display_name' => 'AIモデル価格',
        'description' => 'AIモデルの価格設定を管理します',
        'icon' => 'calculator',
        'sort_order' => 62,
    ],
    'AiProvider' => [
        'display_name' => 'AIプロバイダー',
        'description' => 'AIサービスプロバイダーを管理します',
        'icon' => 'cloud',
        'sort_order' => 63,
    ],
    'Group' => [
        'display_name' => 'グループ管理',
        'description' => 'ユーザーグループを管理します',
        'icon' => 'users-cog',
        'sort_order' => 190,
    ],
    'Memberships' => [
        'display_name' => 'メンバーシップ',
        'description' => 'メンバーシップの定義と権限を管理します',
        'icon' => 'id-card',
        'sort_order' => 46,
    ],
    'VideoCall' => [
        'display_name' => 'ビデオ通話',
        'description' => 'ビデオ通話機能を管理します',
        'icon' => 'video',
        'sort_order' => 32,
    ],
    'DatabaseLog' => [
        'display_name' => 'データベースログ',
        'description' => 'データベース操作ログを参照します',
        'icon' => 'database',
        'sort_order' => 9,
    ],
    'EmailNotification' => [
        'display_name' => 'メール通知',
        'description' => 'メール通知の設定を管理します',
        'icon' => 'mail',
        'sort_order' => 85,
    ],
    'UserPurchasedPlan' => [
        'display_name' => 'ユーザー購入プラン',
        'description' => 'ユーザーが購入したプランを管理します',
        'icon' => 'shopping-cart',
        'sort_order' => 47,
    ],
    'UserPurchasedProduct' => [
        'display_name' => 'ユーザー購入商品',
        'description' => 'ユーザーが購入した商品を管理します',
        'icon' => 'shopping-bag',
        'sort_order' => 48,
    ],
    'UserMemberships' => [
        'display_name' => 'ユーザーメンバーシップ',
        'description' => 'ユーザーのメンバーシップを管理します',
        'icon' => 'user-plus',
        'sort_order' => 49,
    ],
    'Follow' => [
        'display_name' => 'フォロー',
        'description' => 'ユーザー間のフォロー関係を管理します',
        'icon' => 'user-check',
        'sort_order' => 163,
    ],
    'Invite' => [
        'display_name' => '招待',
        'description' => 'ユーザー招待機能を管理します',
        'icon' => 'user-plus',
        'sort_order' => 91,
    ],
    'Reservation' => [
        'display_name' => '予約管理',
        'description' => '予約の作成・管理を行います',
        'icon' => 'calendar-check',
        'sort_order' => 209,
    ],
    'Scenario' => [
        'display_name' => 'シナリオ',
        'description' => '自動応答シナリオを管理します',
        'icon' => 'git-branch',
        'sort_order' => 210,
    ],
    'PusherInfo' => [
        'display_name' => 'Pusher情報',
        'description' => 'Pusherリアルタイム通信設定を管理します',
        'icon' => 'radio',
        'sort_order' => 86,
    ],
    'SignatureInfo' => [
        'display_name' => '署名情報',
        'description' => '署名・電子認証情報を管理します',
        'icon' => 'pen-tool',
        'sort_order' => 211,
    ],
    'Entitlement' => [
        'display_name' => 'エンタイトルメント',
        'description' => 'ユーザーの権限付与・特典を管理します',
        'icon' => 'key-round',
        'sort_order' => 128,
    ],
];
